### ISSUE TITLE
Version issue results in dowloading of DXF libraries on every import.

### ISSUE THREAD

**Issue by Roy-043** [yorikvanhavre/Draft-dxf-importer#25]
In importDXF.py:
`CURRENTDXFLIB = 1.41`

In dxfLibrary.py:
`__version__ = "v1.40 - 2015.09.12"` <= Needs to be updated i suppose.

**Comment by yorikvanhavre** [comment]
oops good catch thanks! Done with https://github.com/yorikvanhavre/Draft-dxf-importer/commit/25931033397a4bdfbf62cdca4393609022752f57
