### ISSUE TITLE
DXF Library Location reference needs updated in ReadMe

### ISSUE THREAD

**Issue by jonesjt** [yorikvanhavre/Draft-dxf-importer#4]
The ReadMe.md file lists C:\Users\yourUser\Application Data\FreeCAD as the correct location for the *.py files that are part of the dxf 'library'.  On Windows 7 the proper location is C:\Users\[username]\AppData\Roaming\FreeCAD, or at least that is where I had to place the *.py files in order for  the export to work and not complain about the library download failing.

**Comment by marc22alain** [comment]
A similar issue exists for the OSX distribution.
I needed to create the HOME/.FreeCAD directory. After copying this library in, the same error occurred.
By the way, the error dialog reports that the library should reside in the 'macros' folder.
There is no such folder created, either in the application package, or in any structure in the user directory.
![screen shot 2015-09-08 at 10 34 23 pm](https://cloud.githubusercontent.com/assets/3311343/9752069/43d4033c-567a-11e5-9d74-d5951f646c03.png)

Any hints on how to proceed would be appreciated !

**Comment by yorikvanhavre** [comment]
This issue is now solved, and this message will now display further info. As for the macro folder, check the instructions on http://www.freecadweb.org/wiki/index.php?title=Dxf_Importer_Install
