### ISSUE TITLE
DXF import

### ISSUE THREAD

**Issue by jbevan** [yorikvanhavre/Draft-dxf-importer#5]
I have followed the instruction to place the python scripts in the correct folder but unfortunately FreeCad still is not able to import a DXF file.

Platform is FreeCad 0.14 on Windows 7.
The error I get is below:
![image](https://cloud.githubusercontent.com/assets/9464816/4846256/911a8908-604a-11e4-8eac-8e80dcfecc65.png)

Any support in resolving this would be greatly appreciated.

**Comment by rammstan** [comment]
Hello, i habe the same problem than Jbevan with win7 and 0.14

**Comment by yorikvanhavre** [comment]
Sorry guys, only now I see these issues...
If someone here is stil having this issue, could you please share a DXF file that cause the problem?
Thanks
