### ISSUE TITLE
importDXF (v1.38) does not pickup lib without a GUI

### ISSUE THREAD

**Issue by swill** [yorikvanhavre/Draft-dxf-importer#7]
I am using FreeCAD using the daily build (v15) on a system without X installed.  It is a Ubuntu 14.04 server which I dispatch build jobs to.

After fixing the issue I posted in the last issue, I get the following issue.  
```
FreeCAD 0.15, Libs: 0.15R4542 (Git)
DXF libraries not found. Downloading...
The DXF import/export libraries needed by FreeCAD to handle the DXF format
were not found on this system. Please either enable FreeCAD to download these
libraries (menu Edit > Preferences > Import-Export > DXF > Enable downloads) or download
these libraries manually, as explained on
https://github.com/yorikvanhavre/Draft-dxf-importer
```

I have extracted the contents of the 1.38 zip to my ~/.FreeCAD directory, but they apparently do not get picked up.

Also, since I am using this library without any GUI, I can not change the preferences to allow it to download the files.  Maybe that should be turned ON by default?

How can I get past this?  Thanks...

**Comment by swill** [comment]
Ok, now I am a bit confused.  Here is what I am getting when I test manually in the python interpreter...
```
# python
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path.append('/usr/lib/freecad/lib')
>>> import FreeCAD
FreeCAD 0.15, Libs: 0.15R4542 (Git)
>>> import importDXF
DXF libraries not found. Downloading...
The DXF import/export libraries needed by FreeCAD to handle the DXF format
were not found on this system. Please either enable FreeCAD to download these
libraries (menu Edit > Preferences > Import-Export > DXF > Enable downloads) or download
these libraries manually, as explained on
https://github.com/yorikvanhavre/Draft-dxf-importer
>>> print importDXF.CURRENTDXFLIB
1.38
>>> 
```

So it does seem that the 'importDXF' files ARE getting picked up, but for some reason parts of the code does not recognize them?  I am not sure what is going on here.

I do know that the following export is not working.
```
importDXF.export(FreeCAD.ActiveDocument.Objects, "%s/custom.dxf" % (config['app']['export']))
```

However all of these work.
```
with open("%s/custom.js" % (config['app']['export']), "w") as f:
    cadquery.exporters.exportShape(p, 'TJS', f)
Part.export(FreeCAD.ActiveDocument.Objects, "%s/custom.brp" % (config['app']['export']))
Part.export(FreeCAD.ActiveDocument.Objects, "%s/custom.stp" % (config['app']['export']))
Mesh.export(FreeCAD.ActiveDocument.Objects, "%s/custom.stl" % (config['app']['export']))
```

Ideas on this?

**Comment by yorikvanhavre** [comment]
Sorry, I only see these issues now...
Is this still a problem?
The importDXF script is bundled with FreeCAD. But it doesn't ship the additional python modules from this repo. Once you place them in a place where FreeCAD can import them (in your .FreeCAD folder or in your macros folder - http://www.freecadweb.org/wiki/index.php?title=Dxf_Importer_Install ) they should be importable. To check, just do this:

    import dxfLibrary

If no error apprears, everything should be fine.

**Comment by swill** [comment]
I will have to check tonight, but I think this is fixed in the current code
base.

**Comment by yorikvanhavre** [comment]
Closing this because it's old, please reopen if needed!

**Comment by swill** [comment]
Sorry I didn't follow up on this.  I believe I checked and this was fixed and I just forgot to update you.  Thanks...
